name: Build

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'
      - name: Setup Android build environment
        uses: android-actions/setup-android@v2
      - name: Create debug keystore for android
        run: |
          mkdir -p $HOME/.android
          keytool -genkey -v -keystore $HOME/.android/debug.keystore -storetype PKCS12 -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -noprompt -dname "CN=CollapseTheGame, OU=SimonIT, O=SimonIT, L=Unknown, ST=Unknown, C=DE"
      - name: Build whole project with gradle
        run: ./gradlew build
